### K-Nearest Neighbors (KNN) is a simple yet powerful classification and regression algorithm in machine learning. It belongs to the family of instance-based learning or lazy learning algorithms.

## d(p, q) = sqrt((p1 - q1)^2 + (p2 - q2)^2 + ... + (pd - qd)^2)


In [5]:
import numpy as np
from sklearn import datasets
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target

In [4]:
display(iris_X[:5])
display(iris_y[:5])
X_train,X_test,y_train,y_test = train_test_split(iris_X,iris_y,test_size=0.2)
knn=KNeighborsClassifier()
knn.fit(X_train,y_train)
print(knn.predict(X_test))
print(y_test)

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

array([0, 0, 0, 0, 0])

[0 0 2 2 1 1 2 1 2 2 1 2 2 1 0 2 2 1 0 1 2 0 2 0 1 0 1 1 2 0]
[0 0 2 2 1 1 2 1 2 2 1 2 2 1 0 2 2 1 0 1 2 0 2 0 2 0 1 1 2 0]


In [20]:
# implement 
from collections import Counter
def load_split_random(split_rate=0.8):
    iris = datasets.load_iris()
    shuffle_idx = np.random.permutation(len(iris.data))
    train_size = int(split_rate*len(iris.data))
    
    train_X = iris.data[shuffle_idx[:train_size]]
    train_y = iris.target[shuffle_idx[:train_size]] 
    test_X = iris.data[shuffle_idx[train_size:]]
    test_y = iris.target[shuffle_idx[train_size:]]
    
    return train_X,test_X,train_y,test_y

def KNN(test_X, train_X, k=5):
    pred_y = []
    for x_test_elem in test_X:
        distance = [np.sqrt(np.sum(np.power(X_train_elem - x_test_elem,2))) for X_train_elem in train_X ]
        indexSort = np.argsort(distance)
        nearK_y = [train_y[i] for i in indexSort[:k]]
        count_y = Counter(nearK_y)
        predicted_y = count_y.most_common(1)[0][0]
        pred_y.append(predicted_y)
    return pred_y

def eval_KNN(true_y,pred_y):
    count = np.sum(true_y==pred_y)
    acc_score = count/len(true_y)
    return acc_score

In [23]:
train_X,test_X,train_y,test_y = load_split_random()
pred_y_series =  KNN(test_X,train_X)
acc_score = eval_KNN(test_y,pred_y_series)

In [24]:
acc_score

0.9666666666666667